src/main/resources/static/KnowledgeGraph/js/fvcom.js
src/main/resources/static/KnowledgeGraph/js/swat.js
src/main/resources/static/KnowledgeGraph/js/swmm.js
src/main/resources/static/KnowledgeGraph/js/xajModel.js
src/main/resources/templates/KnowledgeGraph/fvcom.html
src/main/resources/templates/KnowledgeGraph/swat.html
src/main/resources/templates/KnowledgeGraph/swmm.html
src/main/resources/templates/KnowledgeGraph/xajModel.html

解决数据问题以及移动消失问题,解决块隐藏导致的点击不显示问题

解决数据问题以及移动消失问题,解决块隐藏导致的点击不显示问题

---

src/main/resources/static/css/base/index2.css
src/main/resources/static/css/common/navbar.css
src/main/resources/static/js/common/navbar.js
src/main/resources/templates/fragments/navbar.html

navbar add animation        
index modify

wzh 0927 navbar modify:add animation

---

src/main/resources/static/KnowledgeGraph/css/kgstyle.css
src/main/resources/static/KnowledgeGraph/js/fvcom.js
src/main/resources/static/KnowledgeGraph/js/swat.js
src/main/resources/static/KnowledgeGraph/js/swmm.js
src/main/resources/static/KnowledgeGraph/js/xajModel.js
src/main/resources/templates/KnowledgeGraph/ecomsed.html
src/main/resources/templates/KnowledgeGraph/fvcom.html
src/main/resources/templates/KnowledgeGraph/swat.html
src/main/resources/templates/KnowledgeGraph/swmm.html
src/main/resources/templates/KnowledgeGraph/xajModel.html

loading+function

---

src/main/java/njgis/opengms/portal/controller/rest/RepositoryRestController.java
src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/theme_info.html

改进用户信息获取功能

---

src/main/resources/static/css/page/create-theme.css
src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/create-theme.html
src/main/resources/templates/theme_info.html

更新create theme样式，更改为tabs样式

---

src/main/resources/static/css/page/create-theme.css
src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/create-theme.html

解决右侧数据显示问题

---

src/main/resources/static/js/page/create-theme.js

tab名称根据类名改变

---

src/main/resources/static/css/page/load-theme.css
src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/theme_info.html

解决theme_info页面展示的一些问题

---

src/main/resources/static/css/page/create-theme.css
src/main/resources/static/css/page/load-theme.css
src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/create-theme.html

解决tabs名称变化问题，以及去掉confirm按钮

---

src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/create-theme.html

完善删除功能以及追加类名问题

---

src/main/resources/application.properties
src/main/resources/static/js/page/create-theme.js
src/main/resources/templates/create-theme.html

解决add new application的bug，解决application的title变化问题

解决add new application的bug，解决application的title变化问题

---

src/main/resources/static/css/page/load-theme.css

解决theme_info界面右侧渲染bug

---

src/main/java/njgis/opengms/portal/controller/rest/RepositoryRestController.java
src/main/resources/templates/Thematic.html

thematic 增加作者信息

---

src/main/resources/templates/Thematic.html

增加原thematic作者信息

---

src/main/resources/static/js/page/create-theme.js
src/main/resources/static/js/page/load-theme.js
src/main/resources/templates/theme_info.html

修改create theme的tab与显示表格相联系的bug

修改create theme的tab与显示表格相联系的bug

---

src/main/resources/static/js/page/create-theme.js

修改tab的增删改的bug

---

src/main/resources/application.properties
src/main/resources/static/css/other/themeEditor.css
src/main/resources/static/css/page/model_items.css
src/main/resources/static/js/page/create-theme.js
src/main/resources/static/js/page/load-theme.js
src/main/resources/templates/Thematic.html
src/main/resources/templates/create-theme.html
src/main/resources/templates/theme_info.html

修改application的tab增删问题，增加application的判断逻辑

修改application的tab增删问题，增加application的判断逻辑

---

src/main/java/njgis/opengms/portal/controller/rest/UserRestController.java
src/main/java/njgis/opengms/portal/dao/FeedbackDao.java
src/main/java/njgis/opengms/portal/entity/Feedback.java
src/main/java/njgis/opengms/portal/service/UserService.java
src/main/resources/static/js/page/feedBack.js
src/main/resources/static/js/page/userAccount.js
src/main/resources/static/js/page/userDataSpace.js
src/main/resources/templates/feedBack.html
src/main/resources/templates/userAccount.html
src/main/resources/templates/userData.html
src/main/resources/templates/userDataSpace.html
src/main/resources/templates/userModel.html
src/main/resources/templates/userTask.html
src/main/resources/templates/user_page_overview.html

wzh 0208 new userSpace Detail Modify 1.3

---

src/main/java/njgis/opengms/portal/controller/rest/VersionRestController.java
src/main/java/njgis/opengms/portal/entity/ComputableModelVersion.java
src/main/java/njgis/opengms/portal/entity/ConceptVersion.java
src/main/java/njgis/opengms/portal/entity/ConceptualModelVersion.java
src/main/java/njgis/opengms/portal/entity/LogicalModelVersion.java
src/main/java/njgis/opengms/portal/entity/ModelItemVersion.java
src/main/java/njgis/opengms/portal/entity/SpatialReferenceVersion.java
src/main/java/njgis/opengms/portal/entity/TemplateVersion.java
src/main/java/njgis/opengms/portal/entity/UnitVersion.java
src/main/resources/static/css/common/navbar.css
src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/fragments/newSideBar.html
src/main/resources/templates/index.html
src/main/resources/templates/message_confirm.html

timeline 时间线更改

---

src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/message_confirm.html

timeline 时间线更改2

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/java/njgis/opengms/portal/entity/Theme.java
src/main/java/njgis/opengms/portal/entity/support/SubApplication.java
src/main/java/njgis/opengms/portal/entity/support/SubClassInfo.java
src/main/java/njgis/opengms/portal/entity/support/SubDataInfo.java
src/main/java/njgis/opengms/portal/entity/support/SubDetail.java
src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/message_confirm.html

message数据table展示修改，时间格式修改

---

src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/message_confirm.html
src/main/resources/templates/theme_info.html

theme 的view显示优化

---

src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/message_confirm.html
src/main/resources/templates/testmessage.html

专题编辑与消息提示bug改正03.12

---

src/main/resources/static/css/common/navbar.css

专题编辑与消息提示bug改正03.12.2

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java

message_num计数问题

---

src/main/resources/static/js/common/navbar.js
src/main/resources/templates/fragments/navbar.html

导航栏notice计数

---

src/main/java/njgis/opengms/portal/service/RepositoryService.java

theme展示bug

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/java/njgis/opengms/portal/dto/theme/ThemeVersionDTO.java
src/main/resources/static/js/page/message_confirm.js

accept bug

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/java/njgis/opengms/portal/socket/WebSocketConfig.java
src/main/java/njgis/opengms/portal/socket/WebSocketTest.java
src/main/resources/static/css/common/navbar.css
src/main/resources/static/js/common/navbar.js
src/main/resources/static/js/page/create-computable-model.js
src/main/resources/static/js/page/create-concept.js
src/main/resources/static/js/page/create-conceptual-model.js
src/main/resources/static/js/page/create-logical-model.js
src/main/resources/static/js/page/create-modelitem.js
src/main/resources/static/js/page/create-spatialReference.js
src/main/resources/static/js/page/create-template.js
src/main/resources/static/js/page/create-theme.js
src/main/resources/static/js/page/create-unit.js
src/main/resources/static/js/page/message_confirm.js
src/main/resources/static/js/page/newSideBar.js
src/main/resources/static/js/page/theme_info.js
src/main/resources/static/socket/message.js
src/main/resources/templates/create-modelitem.html
src/main/resources/templates/create-theme.html
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/message_confirm.html
src/main/resources/templates/theme_info.html

专题与消息提示第三版（加websocket）

---

src/main/java/njgis/opengms/portal/dao/DataItemDao.java
src/main/java/njgis/opengms/portal/service/DataItemService.java
src/main/resources/static/css/page/message_confirm.css
src/main/resources/static/css/page/theme_info.css
src/main/resources/static/js/page/message_confirm.js
src/main/resources/static/js/page/theme_info.js
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/message_confirm.html
src/main/resources/templates/theme_info.html

Theme debug and message optimization

Theme debug and message optimization

---

src/main/resources/application.properties
src/main/resources/templates/theme_info.html

Theme debug2

---

src/main/resources/application.properties
src/main/resources/static/css/page/theme_info.css
src/main/resources/templates/theme_info.html

theme debug3

---

src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/Thematic.html
src/main/resources/templates/message_confirm.html
src/main/resources/templates/theme_info.html

message debug(oid and modifier_oid)

message debug(oid and modifier_oid)

---

src/main/resources/static/css/common/navbar.css
src/main/resources/templates/fragments/newSideBar.html

newsidebar debug

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/resources/static/js/page/theme_info.js
src/main/resources/templates/theme_info.html

edit debug

---

src/main/resources/templates/theme_info.html

Block spacing

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/java/njgis/opengms/portal/service/ThemeService.java
src/main/java/njgis/opengms/portal/service/UserService.java
src/main/resources/static/js/page/userTheme.js
src/main/resources/templates/userTheme.html

theme delete

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/java/njgis/opengms/portal/dao/ThemeDao.java
src/main/java/njgis/opengms/portal/service/ThemeService.java
src/main/resources/application.properties
src/main/resources/static/css/common/navbar.css
src/main/resources/static/css/page/theme_info.css
src/main/resources/static/js/common/navbar.js
src/main/resources/static/js/page/create-modelitem.js
src/main/resources/static/js/page/newSideBar.js
src/main/resources/static/js/page/userTheme.js
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/fragments/newSideBar.html
src/main/resources/templates/userTheme.html

theme search

---

src/main/resources/static/css/page/theme_info.css
src/main/resources/static/js/page/theme_info.js
src/main/resources/templates/theme_info.html

menu 适配问题2

---

src/main/java/njgis/opengms/portal/controller/rest/CommentController.java
src/main/resources/static/js/page/model_item_info.js
src/main/resources/templates/fragments/comments.html
src/main/resources/templates/message_confirm.html

message comment

---

src/main/java/njgis/opengms/portal/controller/rest/CommentController.java
src/main/java/njgis/opengms/portal/entity/Comment.java
src/main/java/njgis/opengms/portal/service/UserService.java
src/main/resources/static/js/page/message_confirm.js
src/main/resources/static/js/page/newSideBar.js
src/main/resources/templates/message_confirm.html

message的一些更新，包括回复的计数与已阅

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java
src/main/java/njgis/opengms/portal/controller/rest/VersionRestController.java
src/main/java/njgis/opengms/portal/dto/theme/ThemeVersionDTO.java
src/main/java/njgis/opengms/portal/dto/version/VersionDTO.java
src/main/java/njgis/opengms/portal/service/ThemeService.java
src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/message_confirm.html

message的一些更新,myedition

---

src/main/java/njgis/opengms/portal/controller/rest/VersionRestController.java
src/main/java/njgis/opengms/portal/entity/ComputableModelVersion.java
src/main/java/njgis/opengms/portal/entity/ConceptVersion.java
src/main/java/njgis/opengms/portal/entity/ConceptualModelVersion.java
src/main/java/njgis/opengms/portal/entity/LogicalModelVersion.java
src/main/java/njgis/opengms/portal/entity/ModelItemVersion.java
src/main/java/njgis/opengms/portal/entity/MyEdition.java
src/main/java/njgis/opengms/portal/entity/SpatialReferenceVersion.java
src/main/java/njgis/opengms/portal/entity/TemplateVersion.java
src/main/java/njgis/opengms/portal/entity/ThemeVersion.java
src/main/java/njgis/opengms/portal/entity/UnitVersion.java
src/main/java/njgis/opengms/portal/entity/support/Oids.java
src/main/java/njgis/opengms/portal/service/ThemeService.java
src/main/java/njgis/opengms/portal/service/UserService.java
src/main/resources/static/js/page/create-theme.js
src/main/resources/static/js/page/message_confirm.js
src/main/resources/templates/fragments/newSideBar.html
src/main/resources/templates/message_confirm.html
src/main/resources/templates/userSpace1.html

message页面version的已读

---

src/main/resources/static/js/page/message_confirm.js

message debug

---

src/main/resources/static/js/page/data_application.js
src/main/resources/templates/data_application.html
src/main/resources/templates/data_items.html
src/main/resources/templates/data_items_repository.html
src/main/resources/templates/theme_info.html

dataApplication页面

---

src/main/resources/templates/data_items.html
src/main/resources/templates/data_items_network.html
src/main/resources/templates/data_items_repository.html

数据条目展示页面字体大小调整、名称部分调整

---

src/main/resources/static/js/page/userData.js
src/main/resources/templates/data_items_repository.html
src/main/resources/templates/fragments/navbar.html
src/main/resources/templates/userData.html

userData适配

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/service/DataItemService.java
src/main/resources/static/js/common/navbar.js
src/main/resources/static/js/page/create-data-application.js
src/main/resources/static/js/page/create-data-visualApplication.js
src/main/resources/static/js/page/data_application_info.js
src/main/resources/static/js/page/data_item_info.js
src/main/resources/static/js/page/userDataApplication.js
src/main/resources/static/js/page/userDataVisualApplication.js
src/main/resources/templates/create-data-application.html
src/main/resources/templates/create-data-visualApplication.html
src/main/resources/templates/data_application_info.html
src/main/resources/templates/userData.html

application 修正

---

src/main/resources/templates/userData.html

user data 样式问题

---

src/main/java/njgis/opengms/portal/controller/rest/ThemeRestController.java

theme maintainer

---

src/main/resources/templates/data_application.html

application

---

src/main/java/njgis/opengms/portal/dto/DataApplicationDTO.java
src/main/java/njgis/opengms/portal/entity/DataApplication.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/resources/static/js/page/create-data-application.js
src/main/resources/templates/create-data-application.html
src/main/resources/templates/data_application_info.html

InvokeService

---

pom.xml
src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/controller/rest/DataItemRestController.java
src/main/java/njgis/opengms/portal/dao/DataApplicationDao.java
src/main/java/njgis/opengms/portal/dto/dataApplication/DataApplicationDTO.java
src/main/java/njgis/opengms/portal/entity/DataApplication.java
src/main/java/njgis/opengms/portal/entity/support/Application.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/java/njgis/opengms/portal/entity/support/MetaData.java
src/main/java/njgis/opengms/portal/entity/support/TestData.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/java/njgis/opengms/portal/utils/DataApplicationUtil.java
src/main/resources/static/js/page/create-data-application.js
src/main/resources/static/js/page/create-dataItem.js
src/main/resources/templates/create-data-application.html
src/main/resources/templates/userData.html

deploy data package

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/dao/DataApplicationDao.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java

invoke data package

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/resources/static/js/page/data_application_info.js
src/main/resources/static/js/page/data_application_task.js
src/main/resources/templates/data_application_info.html
src/main/resources/templates/data_application_repository.html
src/main/resources/templates/data_application_task.html

invoke data package 第一版

---

src/main/java/njgis/opengms/portal/entity/DataApplication.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/resources/static/js/page/create-data-application.js
src/main/resources/templates/create-data-application.html

invoke data package 优化

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/dao/DataApplicationDao.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/java/njgis/opengms/portal/service/DataItemService.java
src/main/resources/static/js/page/create-theme.js
src/main/resources/static/js/page/data_application_info.js
src/main/resources/static/js/page/data_application_task.js
src/main/resources/templates/create-theme.html
src/main/resources/templates/data_application_info.html
src/main/resources/templates/data_application_task.html

加入invoke bind

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/dao/DataApplicationDao.java
src/main/java/njgis/opengms/portal/entity/support/InvokeService.java
src/main/java/njgis/opengms/portal/entity/support/TestData.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/java/njgis/opengms/portal/service/DataServerService.java
src/main/java/njgis/opengms/portal/utils/Tools.java
src/main/resources/static/js/page/create-dataItem.js
src/main/resources/static/js/page/data_application_info.js
src/main/resources/static/js/page/data_application_task.js
src/main/resources/static/js/page/userDataServer.js
src/main/resources/templates/create-dataItem.html
src/main/resources/templates/data_application_info.html
src/main/resources/templates/data_application_task.html

InvokeService 完善

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/entity/DataServerTask.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/resources/static/js/page/data_application_info.js
src/main/resources/static/js/page/data_application_task.js
src/main/resources/templates/create-data-application.html
src/main/resources/templates/data_application_task.html

基础版dataServer

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/dao/DataServerTaskDao.java
src/main/java/njgis/opengms/portal/entity/DataServerTask.java
src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/resources/static/js/page/data_application_task.js
src/main/resources/static/js/page/userDataApplication.js
src/main/resources/templates/data_application_task.html
src/main/resources/templates/userDataApplication.html
src/main/resources/templates/userDataHubs.html
src/main/resources/templates/userDataItems.html

DataServer改进版，加入task与可视化

---

src/main/java/njgis/opengms/portal/service/DataApplicationService.java
src/main/resources/static/js/page/data_application_task.js
src/main/resources/templates/data_application_task.html

dataServer改进版1.7

---

src/main/java/njgis/opengms/portal/controller/rest/DataItemRestController.java
src/main/java/njgis/opengms/portal/service/DataItemService.java
src/main/resources/templates/userTask.html

部分bug修正113

---

src/main/java/njgis/opengms/portal/controller/rest/DataApplicationController.java
src/main/java/njgis/opengms/portal/controller/rest/DataItemRestController.java
src/main/java/njgis/opengms/portal/entity/OutputDataTask.java
src/main/java/njgis/opengms/portal/service/DataItemService.java
src/main/resources/static/js/page/create-data-application.js
src/main/resources/static/js/page/create-theme.js
src/main/resources/static/js/page/data_item_info.js
src/main/resources/static/js/page/theme_info.js
src/main/resources/static/js/page/userTheme.js
src/main/resources/static/js/page/userspaceTask.js
src/main/resources/templates/create-data-application.html
src/main/resources/templates/create-theme.html
src/main/resources/templates/data_application_info.html
src/main/resources/templates/data_application_task.html

1.15/19.15
